# Change these first
owner: ME-Software-Tools # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Frontend - GWUI Dev
    url: http://gwui-dev.generic-webui.iiot.dev.yacoub.de/
  - name: Frontend - GWUI Release
    url: http://murr.generic-webui.iiot.dev.yacoub.de/
  - name: ------------------------
    url: http://google1.com/
  - name: Backend - Virtual Xelity Release
    url: http://xelity-backend.generic-webui.iiot.dev.yacoub.de/
  - name: Backend - Virtual MVK Release
    url: http://mvk-backend.generic-webui.iiot.dev.yacoub.de/
  - name: Backend - Virtual VarioX Release
    url: http://variox-backend.generic-webui.iiot.dev.yacoub.de/
  - name: ------------------------
    url: http://google2.com/
  - name: Real VarioX 
    url: https://variox1-bln.thingsgate.dev.yacoub.de/api/
  - name: Real Xelity (don't use ssl)
    url: http://xelity-bln.thingsgate.dev.yacoub.de/#!/login
  - name: ------------------------
    url: http://google3.com/
  - name: Backend - Virtual PremiumIO 
    url: http://premiumio-backend.generic-webui.iiot.dev.yacoub.de/
  - name: ------------------------
    url: http://google4.com/
  - name: SPS23 Variox LNI aas-edge
    url: http://variox3-lni.thingsgate.dev.yacoub.de/api/NetworkConfiguration
  - name: SPS23 Averto LNI Server
    url: https://ca-lni-emsfrontend-dev-001.gentlerock-dced5219.northeurope.azurecontainerapps.io
  - name: Frontend - IIOT-Portal
    url: http://staging.iiot.dev.yacoub.de/
  - name: Backend - IIOT-Portal
    url: http://staging-iiot-api-gateway.iiot.dev.yacoub.de/
    
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://me-software-tools.github.io/upptime/
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
